merge upstream v6.15.0

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,66 +1,53 @@
 #!/bin/bash
 
-(
-  set -e
+set -e
 
-  function printStatus {
-      if [ $? -eq 0 ]; then
-          echo -e "\nSWEET SUITE SUCCESS"
-      else
-          echo -e "\nSUITE FAILURE"
-      fi
-  }
-
-  trap printStatus EXIT
-
-  bin/generate-language-resources
-
-  echo -e "\n Running gi18n checkup..."
-  bin/gi18n-checkup
-
-  go get github.com/tools/godep
-
-  GODEP=$(which godep)
-
-  echo -e "\n Cleaning build artifacts..."
-
-  # Clean up old plugin binaries used in test
-
-  rm -f fixtures/plugins/*.exe
-  rm -f plugin_examples/*.exe
-
-  # Clean up old .a files in GOPATH
-  # It seems like `go clean` should do this but ... not so much
-  if [[ -d $GOPATH/pkg ]] ; then
-    pushd $GOPATH/pkg
-    rm -Rf *
-    popd
+function printStatus {
+  if [ $? -eq 0 ]; then
+    echo -e "\nSWEET SUITE SUCCESS"
+  else
+    echo -e "\nSUITE FAILURE"
   fi
+}
 
-  if [[ -d $($GODEP path)/pkg ]] ; then
-    pushd $($GODEP path)/pkg
-    rm -Rf *
-    popd
-  fi
+trap printStatus EXIT
 
-  export LC_ALL="en_US.UTF-8"
-  export GOPATH=$($GODEP path):$GOPATH
-  export PATH=$($GODEP path)/bin:$PATH
-  go install github.com/onsi/ginkgo/ginkgo
+bin/generate-language-resources
 
-  echo -e "\n Formatting packages..."
-  go fmt ./...
+echo -e "\n Running i18n checkup..."
+bin/i18n-checkup
 
-  echo -e "\n Testing packages..."
-  CF_HOME=$(pwd)/fixtures ginkgo -r $@
+export GO15VENDOREXPERIMENT=1
 
-  echo -e "\n Vetting packages for potential issues..."
-  go tool vet cf/.
-  for file in $(find {cf,fileutils,generic,glob,main,testhelpers,words} \( -name "*.go" -not -iname "*test.go" \))
-  do
-    go tool vet -all -shadow=true $file
-  done
+echo -e "\n Cleaning build artifacts..."
 
-  echo -e "\n Running build script to confirm everything compiles..."
-  bin/build
-)
+# Clean up old plugin binaries used in test
+
+rm -f fixtures/plugins/*.exe
+rm -f plugin_examples/*.exe
+
+export LC_ALL="en_US.UTF-8"
+
+if [ ! $(which ginkgo) ];then
+  echo -e "\n Installing ginkgo..."
+  go get github.com/onsi/ginkgo/ginkgo
+fi
+
+echo -e "\n Formatting packages..."
+go fmt ./...
+
+echo -e "\n Vetting packages for potential issues..."
+go tool vet cf/.
+for file in $(find {cf,commands_loader,downloader,generic,glob,main,plugin,testhelpers,utils,words} \( -name "*.go" -not -iname "*test.go" \))
+do
+  go tool vet -all -shadow=true $file
+done
+
+echo -e "\n Verifying total commands registered..."
+ginkgo commands_loader
+
+echo -e "\n Testing packages..."
+CF_HOME=$(pwd)/fixtures ginkgo -r -p -nodes=4 -randomizeAllSpecs $@
+
+echo -e "\n Running build script to confirm everything compiles..."
+bin/build
